import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/\\[locale\\]/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/\\[locale\\]/books/\\[id\\]/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  // Force-include custom classes that live inside [locale] dynamic segments
  // (fast-glob bracket handling varies across platforms)
  safelist: [
    // --- Typography: font family ---
    'font-headline-xl','font-headline-lg','font-headline-lg-mobile',
    'font-headline-md','font-headline-sm',
    'font-body-lg','font-body-md','font-body-sm',
    'font-label-md','font-label-sm',
    // --- Typography: font size ---
    'text-headline-xl','text-headline-lg','text-headline-lg-mobile',
    'text-headline-md','text-headline-sm',
    'text-body-lg','text-body-md','text-body-sm',
    'text-label-md','text-label-sm',
    // Responsive typography
    'md:font-headline-xl','md:font-headline-lg-mobile',
    'md:text-headline-xl','md:text-headline-lg-mobile',
    'md:hidden','md:block',
    // --- Spacing ---
    'px-margin-mobile','px-margin-desktop','md:px-margin-desktop',
    'p-gutter','px-gutter','py-gutter','gap-gutter',
    'max-w-container-max',
    'pt-24','pb-24','pb-20','pt-8','pb-8',
    // --- Text colours ---
    'text-primary','text-on-primary','text-on-primary-container',
    'text-on-surface','text-on-surface-variant','text-on-background',
    'text-on-secondary-container','text-outline',
    'text-status-available','text-status-borrowed',
    'text-error','text-text-main',
    // --- Background colours ---
    'bg-primary','bg-primary-container',
    'bg-surface','bg-background',
    'bg-surface-container','bg-surface-container-low',
    'bg-surface-container-high','bg-surface-container-lowest',
    'bg-surface-container-highest','bg-secondary-container',
    // --- Border colours ---
    'border-primary','border-secondary-container',
    'border-outline-variant',
    { pattern: /^bg-(status-available|error)\/\d+$/ },
    { pattern: /^text-(status-available|error)\/\d+$/ },
    // --- Grid ---
    'md:grid-cols-12','md:grid-cols-2','md:grid-cols-4',
    'lg:grid-cols-3','lg:grid-cols-4',
    'md:col-span-4','md:col-span-8','lg:col-span-3','lg:col-span-9',
    // --- Display / layout ---
    'md:pb-8',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary':                  '#ffffff',
        'surface-container-high':      '#e7e8e9',
        'status-available':            '#2D6A4F',
        'on-primary-container':        '#c0c7ff',
        'secondary-container':         '#cae8ef',
        'surface-bright':              '#f8f9fa',
        'text-main':                   '#1A1C2E',
        'surface-container-lowest':    '#ffffff',
        'error-container':             '#ffdad6',
        'on-tertiary':                 '#ffffff',
        'primary':                     '#475090',
        'on-error':                    '#ffffff',
        'status-borrowed':             '#EF6000',
        'inverse-on-surface':          '#f0f1f2',
        'error':                       '#ba1a1a',
        'secondary':                   '#486369',
        'surface-dim':                 '#d9dadb',
        'outline':                     '#767681',
        'on-background':               '#191c1d',
        'primary-fixed-dim':           '#bcc3ff',
        'surface-tint':                '#50599a',
        'background':                  '#f8f9fa',
        'surface':                     '#f8f9fa',
        'outline-variant':             '#c6c5d1',
        'surface-container':           '#edeeef',
        'inverse-primary':             '#bcc3ff',
        'inverse-surface':             '#2e3132',
        'surface-container-highest':   '#e1e3e4',
        'primary-fixed':               '#dfe0ff',
        'on-primary-fixed-variant':    '#384180',
        'on-secondary':                '#ffffff',
        'on-error-container':          '#93000a',
        'on-surface-variant':          '#464650',
        'surface-variant':             '#e1e3e4',
        'on-secondary-container':      '#4e696f',
        'on-primary-fixed':            '#081253',
        'secondary-fixed':             '#cae8ef',
        'primary-container':           '#475090',
        'on-surface':                  '#191c1d',
        'surface-container-low':       '#f3f4f5',
        'tertiary':                    '#623100',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        unit:             '8px',
        'margin-mobile':  '16px',
        'margin-desktop': '48px',
        gutter:           '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-xl':       ['Montserrat', 'sans-serif'],
        'headline-lg':       ['Montserrat', 'sans-serif'],
        'headline-lg-mobile':['Montserrat', 'sans-serif'],
        'headline-md':       ['Montserrat', 'sans-serif'],
        'headline-sm':       ['Montserrat', 'sans-serif'],
        'body-lg':           ['Hanken Grotesk', 'sans-serif'],
        'body-md':           ['Hanken Grotesk', 'sans-serif'],
        'body-sm':           ['Hanken Grotesk', 'sans-serif'],
        'label-md':          ['Hanken Grotesk', 'sans-serif'],
        'label-sm':          ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-xl':        ['2.25rem',    { lineHeight: '1.2',  fontWeight: '700' }],
        'headline-lg':        ['1.875rem',   { lineHeight: '1.3',  fontWeight: '700' }],
        'headline-lg-mobile': ['1.5rem',     { lineHeight: '1.35', fontWeight: '700' }],
        'headline-md':        ['1.5rem',     { lineHeight: '1.35', fontWeight: '600' }],
        'headline-sm':        ['1.125rem',   { lineHeight: '1.4',  fontWeight: '600' }],
        'body-lg':            ['1rem',       { lineHeight: '1.6'  }],
        'body-md':            ['0.875rem',   { lineHeight: '1.5'  }],
        'body-sm':            ['0.8125rem',  { lineHeight: '1.5'  }],
        'label-md':           ['0.875rem',   { lineHeight: '1.25', fontWeight: '500' }],
        'label-sm':           ['0.75rem',    { lineHeight: '1.25', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};

export default config;
